modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="noob"
version="1.3.0"
displayName="The Game of Noobs"
credits="Created using mod maker MCreator - https://mcreator.net/about. Noob skin from https://www.minecraftskins.com/skin/20735075/noob/"
displayURL="https://github.com/AwesomeKalin/the-game-of-noobs"
updateJSONURL="https://update.awesomekalin.eu.org/noob.json"
authors="AwesomeKalin55, AwesomeFootball 123"
description='''
The mod for noobs. DO NOT USE IF YOU ARE A PRO
'''

[[dependencies.noob]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




