modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="noob"
version="1.4.0"
displayName="The Game of Noobs"
credits="Created using mod maker MCreator - https://mcreator.net/about. Noob skin from https://www.minecraftskins.com/skin/20735075/noob/"
displayURL="https://github.com/AwesomeKalin/the-game-of-noobs"
updateJSONURL="https://update.awesomekalin.eu.org/noob.json"
authors="AwesomeKalin55, AwesomeFootball 123"
description='''
The mod for noobs. DO NOT USE IF YOU ARE A PRO
'''

[[dependencies.noob]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.noob]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.26]"
    ordering="NONE"
    side="BOTH"



